// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v3.20.3
// source: shortUrl/v1/shortUrl.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationShortUrlCreateShortUrl = "/api.shortUrl.v1.ShortUrl/CreateShortUrl"
const OperationShortUrlGetUrl = "/api.shortUrl.v1.ShortUrl/GetUrl"

type ShortUrlHTTPServer interface {
	CreateShortUrl(context.Context, *CreateShortUrlRequest) (*CreateShortUrlReply, error)
	GetUrl(context.Context, *GetUrlRequest) (*GetUrlReply, error)
}

func RegisterShortUrlHTTPServer(s *http.Server, srv ShortUrlHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/shorturl", _ShortUrl_CreateShortUrl0_HTTP_Handler(srv))
	r.GET("/v1/{shortUrl}", _ShortUrl_GetUrl0_HTTP_Handler(srv))
}

func _ShortUrl_CreateShortUrl0_HTTP_Handler(srv ShortUrlHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateShortUrlRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShortUrlCreateShortUrl)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateShortUrl(ctx, req.(*CreateShortUrlRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateShortUrlReply)
		return ctx.Result(200, reply)
	}
}

func _ShortUrl_GetUrl0_HTTP_Handler(srv ShortUrlHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUrlRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShortUrlGetUrl)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUrl(ctx, req.(*GetUrlRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUrlReply)
		return ctx.Result(200, reply)
	}
}

type ShortUrlHTTPClient interface {
	CreateShortUrl(ctx context.Context, req *CreateShortUrlRequest, opts ...http.CallOption) (rsp *CreateShortUrlReply, err error)
	GetUrl(ctx context.Context, req *GetUrlRequest, opts ...http.CallOption) (rsp *GetUrlReply, err error)
}

type ShortUrlHTTPClientImpl struct {
	cc *http.Client
}

func NewShortUrlHTTPClient(client *http.Client) ShortUrlHTTPClient {
	return &ShortUrlHTTPClientImpl{client}
}

func (c *ShortUrlHTTPClientImpl) CreateShortUrl(ctx context.Context, in *CreateShortUrlRequest, opts ...http.CallOption) (*CreateShortUrlReply, error) {
	var out CreateShortUrlReply
	pattern := "/v1/shorturl"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShortUrlCreateShortUrl))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShortUrlHTTPClientImpl) GetUrl(ctx context.Context, in *GetUrlRequest, opts ...http.CallOption) (*GetUrlReply, error) {
	var out GetUrlReply
	pattern := "/v1/{shortUrl}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShortUrlGetUrl))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
