// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: shortUrl/v1/shortUrl.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongUrl string `protobuf:"bytes,1,opt,name=longUrl,proto3" json:"longUrl,omitempty"`
}

func (x *CreateShortUrlRequest) Reset() {
	*x = CreateShortUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShortUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortUrlRequest) ProtoMessage() {}

func (x *CreateShortUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortUrlRequest.ProtoReflect.Descriptor instead.
func (*CreateShortUrlRequest) Descriptor() ([]byte, []int) {
	return file_shortUrl_v1_shortUrl_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortUrlRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type CreateShortUrlReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
}

func (x *CreateShortUrlReply) Reset() {
	*x = CreateShortUrlReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShortUrlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortUrlReply) ProtoMessage() {}

func (x *CreateShortUrlReply) ProtoReflect() protoreflect.Message {
	mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortUrlReply.ProtoReflect.Descriptor instead.
func (*CreateShortUrlReply) Descriptor() ([]byte, []int) {
	return file_shortUrl_v1_shortUrl_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortUrlReply) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type UpdateShortUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateShortUrlRequest) Reset() {
	*x = UpdateShortUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateShortUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShortUrlRequest) ProtoMessage() {}

func (x *UpdateShortUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShortUrlRequest.ProtoReflect.Descriptor instead.
func (*UpdateShortUrlRequest) Descriptor() ([]byte, []int) {
	return file_shortUrl_v1_shortUrl_proto_rawDescGZIP(), []int{2}
}

type UpdateShortUrlReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateShortUrlReply) Reset() {
	*x = UpdateShortUrlReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateShortUrlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShortUrlReply) ProtoMessage() {}

func (x *UpdateShortUrlReply) ProtoReflect() protoreflect.Message {
	mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShortUrlReply.ProtoReflect.Descriptor instead.
func (*UpdateShortUrlReply) Descriptor() ([]byte, []int) {
	return file_shortUrl_v1_shortUrl_proto_rawDescGZIP(), []int{3}
}

type DeleteShortUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteShortUrlRequest) Reset() {
	*x = DeleteShortUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShortUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortUrlRequest) ProtoMessage() {}

func (x *DeleteShortUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortUrlRequest.ProtoReflect.Descriptor instead.
func (*DeleteShortUrlRequest) Descriptor() ([]byte, []int) {
	return file_shortUrl_v1_shortUrl_proto_rawDescGZIP(), []int{4}
}

type DeleteShortUrlReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteShortUrlReply) Reset() {
	*x = DeleteShortUrlReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShortUrlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortUrlReply) ProtoMessage() {}

func (x *DeleteShortUrlReply) ProtoReflect() protoreflect.Message {
	mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortUrlReply.ProtoReflect.Descriptor instead.
func (*DeleteShortUrlReply) Descriptor() ([]byte, []int) {
	return file_shortUrl_v1_shortUrl_proto_rawDescGZIP(), []int{5}
}

type GetUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
}

func (x *GetUrlRequest) Reset() {
	*x = GetUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlRequest) ProtoMessage() {}

func (x *GetUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlRequest.ProtoReflect.Descriptor instead.
func (*GetUrlRequest) Descriptor() ([]byte, []int) {
	return file_shortUrl_v1_shortUrl_proto_rawDescGZIP(), []int{6}
}

func (x *GetUrlRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetUrlReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongUrl string `protobuf:"bytes,1,opt,name=longUrl,proto3" json:"longUrl,omitempty"`
}

func (x *GetUrlReply) Reset() {
	*x = GetUrlReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUrlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlReply) ProtoMessage() {}

func (x *GetUrlReply) ProtoReflect() protoreflect.Message {
	mi := &file_shortUrl_v1_shortUrl_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlReply.ProtoReflect.Descriptor instead.
func (*GetUrlReply) Descriptor() ([]byte, []int) {
	return file_shortUrl_v1_shortUrl_proto_rawDescGZIP(), []int{7}
}

func (x *GetUrlReply) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

var File_shortUrl_v1_shortUrl_proto protoreflect.FileDescriptor

var file_shortUrl_v1_shortUrl_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a,
	0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c,
	0x22, 0x31, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55,
	0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x72, 0x6c, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x34, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52,
	0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x27, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x55, 0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x6e, 0x67,
	0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55,
	0x72, 0x6c, 0x32, 0xa3, 0x03, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12,
	0x77, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72,
	0x6c, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55,
	0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x3a, 0x01, 0x2a, 0x22, 0x0c, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x12, 0x5e, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5e, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5e, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x55,
	0x72, 0x6c, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x7b, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x7d, 0x42, 0x30, 0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1b, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x55, 0x72, 0x6c, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_shortUrl_v1_shortUrl_proto_rawDescOnce sync.Once
	file_shortUrl_v1_shortUrl_proto_rawDescData = file_shortUrl_v1_shortUrl_proto_rawDesc
)

func file_shortUrl_v1_shortUrl_proto_rawDescGZIP() []byte {
	file_shortUrl_v1_shortUrl_proto_rawDescOnce.Do(func() {
		file_shortUrl_v1_shortUrl_proto_rawDescData = protoimpl.X.CompressGZIP(file_shortUrl_v1_shortUrl_proto_rawDescData)
	})
	return file_shortUrl_v1_shortUrl_proto_rawDescData
}

var file_shortUrl_v1_shortUrl_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_shortUrl_v1_shortUrl_proto_goTypes = []interface{}{
	(*CreateShortUrlRequest)(nil), // 0: api.shortUrl.v1.CreateShortUrlRequest
	(*CreateShortUrlReply)(nil),   // 1: api.shortUrl.v1.CreateShortUrlReply
	(*UpdateShortUrlRequest)(nil), // 2: api.shortUrl.v1.UpdateShortUrlRequest
	(*UpdateShortUrlReply)(nil),   // 3: api.shortUrl.v1.UpdateShortUrlReply
	(*DeleteShortUrlRequest)(nil), // 4: api.shortUrl.v1.DeleteShortUrlRequest
	(*DeleteShortUrlReply)(nil),   // 5: api.shortUrl.v1.DeleteShortUrlReply
	(*GetUrlRequest)(nil),         // 6: api.shortUrl.v1.GetUrlRequest
	(*GetUrlReply)(nil),           // 7: api.shortUrl.v1.GetUrlReply
}
var file_shortUrl_v1_shortUrl_proto_depIdxs = []int32{
	0, // 0: api.shortUrl.v1.ShortUrl.CreateShortUrl:input_type -> api.shortUrl.v1.CreateShortUrlRequest
	2, // 1: api.shortUrl.v1.ShortUrl.UpdateShortUrl:input_type -> api.shortUrl.v1.UpdateShortUrlRequest
	4, // 2: api.shortUrl.v1.ShortUrl.DeleteShortUrl:input_type -> api.shortUrl.v1.DeleteShortUrlRequest
	6, // 3: api.shortUrl.v1.ShortUrl.GetUrl:input_type -> api.shortUrl.v1.GetUrlRequest
	1, // 4: api.shortUrl.v1.ShortUrl.CreateShortUrl:output_type -> api.shortUrl.v1.CreateShortUrlReply
	3, // 5: api.shortUrl.v1.ShortUrl.UpdateShortUrl:output_type -> api.shortUrl.v1.UpdateShortUrlReply
	5, // 6: api.shortUrl.v1.ShortUrl.DeleteShortUrl:output_type -> api.shortUrl.v1.DeleteShortUrlReply
	7, // 7: api.shortUrl.v1.ShortUrl.GetUrl:output_type -> api.shortUrl.v1.GetUrlReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shortUrl_v1_shortUrl_proto_init() }
func file_shortUrl_v1_shortUrl_proto_init() {
	if File_shortUrl_v1_shortUrl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shortUrl_v1_shortUrl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShortUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shortUrl_v1_shortUrl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShortUrlReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shortUrl_v1_shortUrl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateShortUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shortUrl_v1_shortUrl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateShortUrlReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shortUrl_v1_shortUrl_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShortUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shortUrl_v1_shortUrl_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShortUrlReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shortUrl_v1_shortUrl_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shortUrl_v1_shortUrl_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUrlReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shortUrl_v1_shortUrl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortUrl_v1_shortUrl_proto_goTypes,
		DependencyIndexes: file_shortUrl_v1_shortUrl_proto_depIdxs,
		MessageInfos:      file_shortUrl_v1_shortUrl_proto_msgTypes,
	}.Build()
	File_shortUrl_v1_shortUrl_proto = out.File
	file_shortUrl_v1_shortUrl_proto_rawDesc = nil
	file_shortUrl_v1_shortUrl_proto_goTypes = nil
	file_shortUrl_v1_shortUrl_proto_depIdxs = nil
}
