// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"shortUrl/internal/biz"
	"shortUrl/internal/conf"
	"shortUrl/internal/data"
	"shortUrl/internal/server"
	"shortUrl/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewSequenceDataBase(confData, logger)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	shortRepo := data.NewShortRepo(dataData, logger)
	shortUrlUsecase := biz.NewShortUsecase(shortRepo, logger)
	shortUrlService := service.NewShortUrlService(shortUrlUsecase)
	grpcServer := server.NewGRPCServer(confServer, shortUrlService, logger)
	httpServer := server.NewHTTPServer(confServer, shortUrlService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
